### ISSUE TITLE
The name of crates have been renamed with `rustc_ap_` prefix

### ISSUE THREAD

**Issue by topecongiro** [alexcrichton/rustc-auto-publish#13]
For example, the following snippets show the part of Cargo.toml of `rustc-ap-syntax` 583.0.0 and 605.0.0:

```toml
[package]
edition = "2018"
name = "rustc-ap-syntax"
version = "583.0.0"
authors = ["The Rust Project Developers"]
description = "Automatically published version of the package `syntax` in the rust-lang/rust repository from commit f7b05af814f02681d8973438df4ed5792f581841 The publishing script for this crate lives at: https://github.com/alexcrichton/rustc-auto-publish\n            "
license = "MIT / Apache-2.0"
repository = "https://github.com/rust-lang/rust"

[lib]
name = "syntax"
path = "lib.rs"
doctest = false
[dependencies.bitflags]
version = "1.0"
```

```toml
[package]
edition = "2018"
name = "rustc-ap-syntax"
version = "605.0.0"
authors = ["The Rust Project Developers"]
description = "Automatically published version of the package `syntax` in the rust-lang/rust repository from commit c6293e359848c8c7275330719b33ccd168df04c3 The publishing script for this crate lives at: https://github.com/alexcrichton/rustc-auto-publish\n            "
license = "MIT / Apache-2.0"
repository = "https://github.com/rust-lang/rust"

[lib]
path = "lib.rs"
doctest = false
[dependencies.bitflags]
version = "1.0"
```

Note that in the Cargo.toml of 605.0.0, `name = "syntax"` is removed from the `[lib]` section. Hence, the name of the crate has been renamed to `rustc_ap_syntax` from `syntax`. Is this change intentional?
